### PR TITLE
🌶️ argocd 2.0.5 🌶️

### PR DESCRIPTION
**Pull request by eformat**
argocd to latest version 2.0.5
prometheus to latest 0.47.0

tested with UJ in OCP 4.8

### CODE REVIEW

**Comment by ckavili** [comment]
thanks Mike! would you mind also updating the chart version of ArgoCD as `1.1.9` in [bootstrap/Chart.yaml](https://github.com/rht-labs/ubiquitous-journey/blob/master/bootstrap/Chart.yaml#L14) and [bootstrap-master/Chart.yaml](https://github.com/rht-labs/ubiquitous-journey/blob/master/bootstrap-master/Chart.yaml#L14) so they all would be up to date? 🙏

**Comment by eformat** [comment]
> thanks Mike! would you mind also updating the chart version of ArgoCD as `1.1.9` in [bootstrap/Chart.yaml](https://github.com/rht-labs/ubiquitous-journey/blob/master/bootstrap/Chart.yaml#L14) and [bootstrap-master/Chart.yaml](https://github.com/rht-labs/ubiquitous-journey/blob/master/bootstrap-master/Chart.yaml#L14) so they all would be up to date?

hi .. ah yeah ... chicken and egg ... looks https://github.com/redhat-cop/helm-charts/pull/178 got merged before https://github.com/redhat-cop/helm-charts/pull/177 .. lolz 

once .. 177 merges .. i will push updates to Charts to align

**Comment by eformat** [comment]
@ckavili  ... ok .. merged in 1.1.9 on this PR now ...

**Comment by ckavili** [comment]
ohh sorry! it's my fault - didn't see the other one! 🤦🏻‍♀️

**Comment by eformat** [comment]
lolz, erm, i could bump redhat-cop/helm-charts#178 so it skips 1.1.8 chart version .. then update here ? say 1.1.10 ... else the 1.1.9 will be missing the base changes ... hold on

**Comment by eformat** [comment]
OK .. done 

THIS - https://github.com/redhat-cop/helm-charts/pull/177/files
has 1.1.10 now, so if you merge that one

and just updated this PR to 1.1.10 as well ...

**Comment by ckavili** [comment]
thanks again and sorry again for causing such trouble haha🙊 🙈

**Pull request merged**
