### PR TITLE
Update oc create -f- parts

### PR DESCRIPTION
**Pull request by mabulgu**
Leaving oc create -f- may cause json unmarshalling problem while decoding template file.

Screen Shot 2020-07-02 at 01 38 38

Suggested use: oc create -f - (with a space)

### CODE REVIEW

**Comment by ckavili** [comment]
I haven't got this error but can you please check if you get the same error when you run the command for the second time? Because this `unable to recognize..` error is related to the API server not register new ArgoCD CRD fast enough 😔

**Comment by mabulgu** [comment]
The first error message is the cause of the second I suppose since it is a marshaling problem. With some of the terminal extensions (like iterm) or other bashes(like zsh) this "-f-" may cause problems time to time. To use it like "-f -" is the guaranteed way I mean. (I did try to find the ocp examples of ours that uses of create with "-f -" but couldn't.)

**Comment by ckavili** [comment]
Fair enough. Just wanted to point it out :)

**Comment by mabulgu** [comment]
Danke schön 🤗

**Pull request merged**
