### PR TITLE
🐕‍  add pelorus 🐕‍

### PR DESCRIPTION
**Pull request by eformat**
add Pelorus

https://github.com/redhat-cop/pelorus

this will also need this to merge for argocd sync to work

https://github.com/redhat-cop/pelorus/pull/135

### CODE REVIEW

**Comment by eformat** [comment]
closes

https://github.com/rht-labs/ubiquitous-journey/issues/115

**Comment by ckavili** [comment]
hey Mike! I see that https://github.com/redhat-cop/pelorus/pull/135 has closed so if you can resolve the conflict, I can merge this in 👍

**Comment by eformat** [comment]
@ckavili - okay .. fixed up conflicts now with head .. cheers

**Comment by ckavili** [comment]
LGTM 🙌🏻

**Pull request merged**
