### PR TITLE
Adds sealed-secrets to the bootstrap chart, disabled by default

### PR DESCRIPTION
**Pull request by jtudelag**

### CODE REVIEW

**Comment by jtudelag** [comment]
Sart to address https://github.com/rht-labs/ubiquitous-journey/issues/131

More PRs to come.

**Comment by springdo** [comment]
@jtudelag - having played with this for a moment, i think this works `condition: sealed-secrets.enabled` on the dep, or at least locally for me it is working

**Comment by springdo** [comment]
I'll probs just merge you in and PR on top if that's ok, I think this requires a readme change too

**Comment by springdo** [comment]
Also - you need to put some Emoji in your commit messages.... otherwise, you may not get merged 😜

**Pull request merged**
