### PR TITLE
💍 Propose init app structure 💍

### PR DESCRIPTION
**Pull request by tylerauerbeck**
WIP: Just proposing an app structure in our `tooling-values.yaml`

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
@springdo @mvmaestri @ckavili @pcarney8 @gsampaio-rh 

So doesn't look like Argo is playing all that nice with remote values files. It looks to pick up the values, but doesn't actually use them. The only way I saw around this was to use the inline values inside of the Argo CR (which I know we wanted to avoid). But at this point, I think it's okay to at least allow for both.

That being said -- if we're using the values files, we had two options. Read them out of a file like we mentioned (which means these files would need to be bundled inside of the chart itself versus being outside of the chart in a normal values file) or we could just dump everything in `tooling-values.yaml` and utilize yaml anchors. 

I know it looks gross, but let me know what everyone thinks. I think we have two approaches here. Just wondering what might be the best one moving forward.

**Comment by ckavili** [comment]
I think it's good to keep values next to charts in the other repo and keep tooling-values.yaml here for Application CR values 🙃 We could also install apps only with helm so it'd be nice to separate it from argo configs 🧐

**Comment by eformat** [comment]
hey @tylerauerbeck i was wondering if this structure works for starters with argo (i think is what you are saying with "dump everything in tooling-values.yaml and utilize yaml anchors")

# tooling chart
Chart.yaml -> has tooling charts as dependencies
values.yaml -> has override values 

that way each subchart has its own values and can be deployed separately

helm3 docs:
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by tylerauerbeck** [comment]
Yeah. I think I was trying to get a bit too fancy there. I like this idea of pulling things in as dependencies (which essentially make them local charts). Then we can just have a an Argo application CR that’s points at our repo and then only provides the specific values for that tool ( I.e. nexus, etc.) so we can still take advantage of the gitopsy goodness. My thinking is that if we only pull in things as dependencies it just turns into what we have now (only a one time run). I’ll get my terrible example updated to go this route and we’ll see what everyone thinks. 

So high level:

Requirements.yaml (because helm 2 until ArgoCD 1.5) -> pull in nexus, Jenkins, etc. similar to what we’re doing with ArgoCD right now

Argo Application CR template -> points to this repo and then we can refer to local values files that hold only values for that specific app (nexus).  Gets us a simplified bootstrapping and a clean values file for each app.

I think I like this, but interested what others think. Happy to demo this a bit tomorrow if anyone is interested.

**Comment by tylerauerbeck** [comment]
This approach also cleans up the whole public/private repo issue down the road. So I think it checks all the boxes of what we would potentially need to handle.

**Pull request merged**
