### PR TITLE
🦆  Minor tweaks to the Argo Deploy that mike created 🦆

### PR DESCRIPTION
**Pull request by springdo**
PR changes from @eformat 's  argocd stuff #83

### CODE REVIEW

**Comment by ckavili** [comment]
> PR changes from @eformat 's argocd stuff #83

``` namespace: {{ .Values.argocd.namespace }}```  should be added to OperatorGroup, Subscription and ArgoCD objects as metadata. Otherwise, ArgoCD is still created in your current namespace :( I pushed that changes to the branch. Can you also please check it?  Because I'm not sure if all these objects are meant to be namespace scoped 🙁

**Comment by eformat** [comment]
@springdo, @ckavili  - i tried this from scratch ... i think it need a little more work in the bootstrap helm project to sync namespace if using completely different name

this worked for me - note the set of bootstrap-project.prefix=my
```
helm template --dependency-update --set argocd.namespace=my-ci-cd --set bootstrap-project.prefix=my -f bootstrap/values-bootstrap.yaml bootstrap  | oc apply -f-
```
so really we can only set the prefix at moment  *-ci-cd, *-dev, *-test, cause if argocd.namespace is something that doesn't match the *-ci-cd pattern it doesn't work

**Comment by springdo** [comment]
Yeah this is something we need to revisit. On Friday we were chatting about removing the prefix stuff completely and just using overrides of the full namespace variable. The prefix stuff was an ansible thing so we can revisit it. This means updating thr bootstrap helm templates for projects and bumping thr versions too

**Comment by eformat** [comment]
+1 🦔🦔🦔 yeah that make a lot more sense to me 🦔🦔🦔

**Comment by springdo** [comment]
This issue here seems to be a bit of a blocker https://github.com/helm/helm/issues/2336  for us to be able to override the NS how we would like to.  Problem is once we override an anchor tag in Yaml it goes straight to the template, but because we're referencing and looping over values it remains at `labs-ci-cd`. We could stick with prefix for now, and raise a new issue to track this helm 'feature' ;)

**Pull request merged**
